### ISSUE TITLE
Falcon versoin

### ISSUE THREAD

**Issue by pqcsf-singlezero** [tidecoin-old/tidecoin#5]
Which version of the falcon signature is used by tidecoin?
The length of the public key of the NIST version is 897 bytes, and the signature is 666 bytes.
The Tidecoin versions are 904 and 659.

**Comment by reorgx** [comment]
Tidecoin uses the implementation in https://falcon-sign.info/index.html. In fact, Tidecoin's public key size is 897 too.  The signature size is variant(in above site, it's 666 for performing test), but not exceeds 690. So the design use in Tidecoin is the same as NIST.
