### ISSUE TITLE
Information about the generation of the genesis key

### ISSUE THREAD

**Issue by neoncoin-project** [tidecoin-old/tidecoin#6]
Hello, first I want to say, very good project! As a developer I've been looking at the code and I really liked how the Falcon implementation was structured. I would like to ask you to add information about how you generated the [genesis key](https://github.com/tidecoin/tidecoin/blob/master/src/chainparams.cpp#L55) since I am trying to implement Falcon in my project and I do not understand how to generate that key. Also I think it would help many developers since Tidecoin is the only Litecoin-based cryptocurrency with a functional implementation of Falcon. Greetings.

**Comment by reorgx** [comment]
It is generated by coding with falcon's original source code. A python lib in github can be used too.
